### ISSUE TITLE
MP3 instead of WebM

### ISSUE THREAD

**Issue by CLykus** [nimiology/spotify_downloader_telegram__bot#10]
Hello!
When a file downloading is finished, I have a WebM file. Of course, I can rename the file (`song*webm -> song*mp3`, but it will be incorrect. If I converted the file, quality of file would be worse.
Can I replace something in `main.py` or `spotify.py` for download MP3 files?

**Comment by nimiology** [comment]
change the mp3 in this line in spotify.py to whatever you want
`                'preferredcodec': 'mp3',
`
